_BASE_: './0212_addxiyuan_registrate_addhead_nodecay.yml'
model:
  embed_dim: 1024
  num_mha_heads: 1
  freeze_backbone: False
loaders:
  train:
    img_file_path: '../../data/train_0212_registrated_5.0.lst'
    text_file_path: '../../data/train_0212_description_5.0.lst'

  test:
    img_file_path: '../../data/test_0212_registrated_5.0.lst'
    text_file_path: '../../data/test_0212_description_5.0.lst'
scheduler:
  n_epochs: 100
  lr_decay_iters: 50
name: 0212_addxiyuan_registrated_filter5_nodecay