_BASE_: './0212_addxiyuan_registrate_addhead.yml'
loaders:
  train:
    img_file_path: '../../data/train_0212_registrated_preoperation.lst'
    text_file_path: '../../data/train_0212_description_preoperation.lst'
  test:
    img_file_path: '../../data/test_0212_registrated_preoperation.lst'
    text_file_path: '../../data/test_0212_description_preoperation.lst'
scheduler:
  n_epochs: 500
  lr_decay_iters: 100
  accumulate_gradient_count: 16
optimizer:
  weight_decay: 0.0001
name: 0212_addxiyuan_registrated_addhead_nodecay_preoperation